const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('markpad', {
  openFile: () => ipcRenderer.invoke('dialog:open'),
  openImage: () => ipcRenderer.invoke('dialog:openImage'),
  openImageData: () => ipcRenderer.invoke('dialog:openImageData'),
  saveFile: (path, content) => ipcRenderer.invoke('file:save', path, content),
  saveFileAs: (content) => ipcRenderer.invoke('dialog:saveAs', content),
  confirmUnsaved: () => ipcRenderer.invoke('dialog:confirmUnsaved'),
  onCloseRequested: (cb) => ipcRenderer.on('close-requested', () => cb()),
  confirmClose: () => ipcRenderer.send('close-confirmed'),
  minimizeWindow: () => ipcRenderer.send('window:minimize'),
  toggleMaximizeWindow: () => ipcRenderer.send('window:toggleMaximize'),
  closeWindow: () => ipcRenderer.send('window:close'),
  onWindowStateChanged: (cb) => ipcRenderer.on('window-state-changed', (_event, state) => cb(state)),
  github: {
    connect: () => ipcRenderer.invoke('github:connect'),
    getAccount: () => ipcRenderer.invoke('github:getAccount'),
    signOut: () => ipcRenderer.invoke('github:signOut'),
    openExternal: (url) => ipcRenderer.invoke('github:openExternal', url),
    onDeviceCode: (cb) => ipcRenderer.on('github:device-code', (_e, payload) => cb(payload)),
    listRepos: () => ipcRenderer.invoke('github:listRepos'),
    listBranches: (repo) => ipcRenderer.invoke('github:listBranches', repo),
    listTree: (repo, branch) => ipcRenderer.invoke('github:listTree', repo, branch),
    readFile: (repo, branch, path) => ipcRenderer.invoke('github:readFile', repo, branch, path),
    commit: (args) => ipcRenderer.invoke('github:commit', args),
    getHead: (repo, branch) => ipcRenderer.invoke('github:getHead', repo, branch),
    fileSha: (repo, branch, path) => ipcRenderer.invoke('github:fileSha', repo, branch, path),
    readAsset: (repo, branch, path) => ipcRenderer.invoke('github:readAsset', repo, branch, path),
    findPullRequest: (repo, branch) => ipcRenderer.invoke('github:findPullRequest', repo, branch),
    createPullRequest: (args) => ipcRenderer.invoke('github:createPullRequest', args),
    createBranch: (repo, name, fromSha) => ipcRenderer.invoke('github:createBranch', repo, name, fromSha),
  },
});
